name: Send Requests Every 10 Minutes

on:
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes

jobs:
  send_requests:
    runs-on: ubuntu-latest

    steps:
      - name: Send request to Website 1
        run: curl -X GET https://harsh-raj-eventspotlite.onrender.com/
      - name: Send request to Website 2
        run: curl -X GET https://harsh-raj-eventspotlite-1.onrender.com/
